#pragma once

#include <cstdint>
#include <string_view>
#include <atomic>
#include <iostream>
#include <cstring>
#include <algorithm>
#include "SceneGraph.h"

// --- Custom Logging Integration Mock ---
#ifndef qCWarning
#define qCWarning(category) std::cerr << "[WARNING] "
#endif

#ifndef qCInfo
#define qCInfo(category) std::cout << "[INFO] "
#endif

#ifndef LogAiBus
struct MockCategoryAi { };
inline MockCategoryAi LogAiBus;
#endif

namespace Genesis {

constexpr uint32_t MaxBusNodes = 2048;
constexpr uint32_t SharedMagicCookie = 0x47454E53; // "GENS"

/**
 * @brief Blit-safe node layout mirroring exactly what the AI agent can "see".
 */
struct alignas(16) AiNodeDescriptor {
    uint32_t id{0xFFFFFFFF};
    float x{0.0f};
    float y{0.0f};
    float width{0.0f};
    float height{0.0f};
    char name[32]{0};
};

/**
 * @brief Shared Virtual Input Command Buffer.
 */
struct alignas(16) AiVirtualInput {
    enum class CommandType : uint32_t { None = 0, MouseClick = 1, TextKey = 2 };
    
    std::atomic<CommandType> type{CommandType::None};
    float targetX{0.0f};
    float targetY{0.0f};
    uint32_t keyPayload{0};
    std::atomic<uint32_t> sequenceId{0};
};

/**
 * @brief Complete Shared Memory Layout representing the physical IPC Segment.
 */
struct alignas(64) SharedBusMemory {
    uint32_t magicCookie;
    std::atomic<uint64_t> telemetryFrameCounter;
    uint32_t nodeCount;
    AiNodeDescriptor nodes[MaxBusNodes];
    AiVirtualInput inboundCommand;
};

/**
 * @brief High-Performance Lock-Free AI Control Bus Manager.
 */
class AiControlBus {
public:
    AiControlBus() : m_sharedRegion(nullptr), m_localSequenceTracker(0) {}
    ~AiControlBus() { detach(); }

    AiControlBus(const AiControlBus&) = delete;
    AiControlBus& operator=(const AiControlBus&) = delete;

    /**
     * @brief Hooks the control bus manager into an existing memory segment.
     */
    void attach(void* memorySegmentSegmentAddress) {
        if (!memorySegmentSegmentAddress) {
            qCWarning(LogAiBus) << "Attempted to attach AI Control Bus to a null memory segment." << std::endl;
            return;
        }

        m_sharedRegion = reinterpret_cast<SharedBusMemory*>(memorySegmentSegmentAddress);
        m_sharedRegion->magicCookie = SharedMagicCookie;
        m_sharedRegion->telemetryFrameCounter.store(0, std::memory_order_release);
        m_sharedRegion->nodeCount = 0;
        
        qCInfo(LogAiBus) << "AI Control Bus attached to memory block successfully." << std::endl;
    }

    void detach() {
        m_sharedRegion = nullptr;
    }

    /**
     * @brief Synchronizes the flat array scene graph nodes down into the AI readable block.
     */
    void updateTelemetry(const class SceneGraph& sceneGraph) {
        if (!m_sharedRegion) return;

        size_t count = std::min(static_cast<size_t>(MaxBusNodes), sceneGraph.totalNodes());
        m_sharedRegion->nodeCount = static_cast<uint32_t>(count);

        for (uint32_t i = 0; i < m_sharedRegion->nodeCount; ++i) {
            auto& targetDest = m_sharedRegion->nodes[i];
            const auto& srcLayout = const_cast<SceneGraph&>(sceneGraph).getLayout(i);

            targetDest.id = i;
            targetDest.x = srcLayout.boundingBox.x;
            targetDest.y = srcLayout.boundingBox.y;
            targetDest.width = srcLayout.boundingBox.width;
            targetDest.height = srcLayout.boundingBox.height;
        }

        m_sharedRegion->telemetryFrameCounter.fetch_add(1, std::memory_order_acq_rel);
    }

    /**
     * @brief Polls for virtual inputs generated by the connected AI controller.
     */
    bool pollInboundCommand(AiVirtualInput& outCommand) {
        if (!m_sharedRegion) return false;

        uint32_t sharedSeq = m_sharedRegion->inboundCommand.sequenceId.load(std::memory_order_acquire);
        if (sharedSeq <= m_localSequenceTracker) {
            return false;
        }

        if (m_sharedRegion->inboundCommand.type.load(std::memory_order_relaxed) == AiVirtualInput::CommandType::None) {
            return false;
        }

        outCommand.type.store(m_sharedRegion->inboundCommand.type.load(std::memory_order_relaxed));
        outCommand.targetX = m_sharedRegion->inboundCommand.targetX;
        outCommand.targetY = m_sharedRegion->inboundCommand.targetY;
        outCommand.keyPayload = m_sharedRegion->inboundCommand.keyPayload;
        
        m_localSequenceTracker = sharedSeq;
        return true;
    }

private:
    SharedBusMemory* m_sharedRegion;
    uint32_t m_localSequenceTracker;
};

} // namespace Genesis
