#!/usr/bin/env python3
"""
embed_spv.py  <shader1.spv> [<shader2.spv> ...] <output.h>

Reads SPIR-V binary files and writes a C++ header with constexpr uint32_t
arrays.  Symbol names are derived from the file name:
    rect.vert.spv   -> kRectVert
    vector.frag.spv -> kVectorFrag
Called automatically by the genesis_shaders CMake target.
"""
import os
import sys


def to_words(path: str) -> list[int]:
    data = open(path, "rb").read()
    while len(data) % 4:
        data += b"\x00"
    return [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]


def symbol_name(path: str) -> str:
    base = os.path.basename(path)
    if base.endswith(".spv"):
        base = base[:-4]
    parts = [p for p in base.split(".") if p]
    return "k" + "".join(p[:1].upper() + p[1:] for p in parts)


def format_array(name: str, words: list[int]) -> list[str]:
    lines = [f"// {name} ({len(words) * 4} bytes)",
             f"inline constexpr uint32_t {name}[{len(words)}] = {{"]
    for i in range(0, len(words), 8):
        lines.append("    " + ", ".join(f"0x{w:08x}u" for w in words[i:i + 8]) + ",")
    lines.append("};")
    return lines


def main() -> None:
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <shader1.spv> [...] <output.h>", file=sys.stderr)
        sys.exit(1)

    spv_files = sys.argv[1:-1]
    out = sys.argv[-1]

    lines: list[str] = [
        "#pragma once",
        "// Auto-generated by cmake/embed_spv.py — do not edit directly.",
        "// Recompile: cmake --build <build-dir> --target genesis_shaders",
        "#include <cstdint>",
        "",
        "inline namespace jf { namespace Shaders {",
        "",
    ]
    for spv in spv_files:
        lines += format_array(symbol_name(spv), to_words(spv)) + [""]
    lines += ["}} // namespace Shaders (in jf)", ""]

    with open(out, "w") as f:
        f.write("\n".join(lines))

    print(f"[shaders] {out}: " + ", ".join(symbol_name(s) for s in spv_files))


if __name__ == "__main__":
    main()
